from typing import Optional, Sequence

import numpy as np
import numpy.typing as npt

IntSamples = npt.NDArray[np.intc]
FloatSamples = npt.NDArray[np.float64]
EntryCounts = npt.NDArray[np.uintc]
BoolSamples = npt.NDArray[np.bool_]
PackedSamples = npt.NDArray[np.uint8]

class SoftError(RuntimeError): ...
SoftCudaError = SoftError

class CpuCircuit:
    def __init__(self, text: Optional[str | bytes] = ..., *, path: object = ..., num_qubits: int = ...) -> None: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def num_measurements(self) -> int: ...
    @property
    def num_detectors(self) -> int: ...
    @property
    def num_observables(self) -> int: ...
    def sample(self, shots: int = ..., num_qubits: int = ..., bit_packed: bool = ...) -> BoolSamples | PackedSamples: ...
    def sample_measurements(self, shots: int = ..., num_qubits: int = ..., bit_packed: bool = ...) -> BoolSamples | PackedSamples: ...
    def sample_detectors(self, shots: int = ..., num_qubits: int = ..., bit_packed: bool = ...) -> BoolSamples | PackedSamples: ...
    def sample_counts(self, shots: int = ..., observable: int = ..., num_qubits: int = ...) -> dict[str, object]: ...

class CudaSimulator:
    def __init__(
        self,
        shot_i: int = ...,
        shots_n: int = ...,
        qubits_n: int = ...,
        entries_m: int = ...,
        mem_ints_n: int = ...,
        mem_flts_n: int = ...,
        epsilon: float = ...,
        seed: int = ...,
    ) -> None: ...
    @property
    def args(self) -> dict[str, int | float]: ...
    @property
    def shots_n(self) -> int: ...
    @property
    def qubits_n(self) -> int: ...
    @property
    def entries_m(self) -> int: ...
    @property
    def mem_ints_n(self) -> int: ...
    @property
    def mem_flts_n(self) -> int: ...
    @property
    def epsilon(self) -> float: ...
    def close(self) -> None: ...
    def synchronize(self) -> None: ...
    def apply_x(self, target: int) -> None: ...
    def apply_y(self, target: int) -> None: ...
    def apply_z(self, target: int) -> None: ...
    def apply_h(self, target: int) -> None: ...
    def apply_s(self, target: int) -> None: ...
    def apply_sdg(self, target: int) -> None: ...
    def apply_t(self, target: int) -> None: ...
    def apply_tdg(self, target: int) -> None: ...
    def apply_cx(self, control: int, target: int) -> None: ...
    def apply_measure(self, target: int) -> None: ...
    def apply_desire(self, target: int, value: int) -> None: ...
    def apply_reset(self, target: int, value: int) -> None: ...
    def apply_noise_x(self, probability: float, target: int) -> None: ...
    def apply_noise_z(self, probability: float, target: int) -> None: ...
    def apply_noise_depo1(self, probability: float, target: int) -> None: ...
    def apply_noise_depo2(self, probability: float, target0: int, target1: int) -> None: ...
    def apply_classical_flip(self) -> None: ...
    def apply_classical_random_flip(self, probability: float) -> None: ...
    def apply_classical_check(self, error: int) -> None: ...
    def apply_classical_load_int(self, pointer: int) -> None: ...
    def apply_classical_load_flt(self, pointer: int) -> None: ...
    def apply_classical_save_int(self, pointer: int) -> None: ...
    def apply_classical_save_flt(self, pointer: int) -> None: ...
    def apply_classical_or(self, pointers: Sequence[int]) -> None: ...
    def apply_classical_xor(self, pointers: Sequence[int]) -> None: ...
    def apply_classical_and(self, pointers: Sequence[int]) -> None: ...
    def apply_classical_match(self, pointers: Sequence[int], values: Sequence[int]) -> None: ...
    def apply_classical_controlled_x(self, target: int) -> None: ...
    def apply_classical_controlled_y(self, target: int) -> None: ...
    def apply_classical_controlled_z(self, target: int) -> None: ...
    def x(self, target: int) -> None: ...
    def y(self, target: int) -> None: ...
    def z(self, target: int) -> None: ...
    def h(self, target: int) -> None: ...
    def s(self, target: int) -> None: ...
    def sdg(self, target: int) -> None: ...
    def t(self, target: int) -> None: ...
    def tdg(self, target: int) -> None: ...
    def cx(self, control: int, target: int) -> None: ...
    def measure(self, target: int) -> None: ...
    def desire(self, target: int, value: int) -> None: ...
    def reset(self, target: int, value: int) -> None: ...
    def work_int(self) -> IntSamples: ...
    def work_float(self) -> FloatSamples: ...
    def errors(self) -> IntSamples: ...
    def entries_n(self) -> EntryCounts: ...
BoolSamples = npt.NDArray[np.bool_]
PackedSamples = npt.NDArray[np.uint8]
    def memory_ints(self, pointer: Optional[int] = ...) -> IntSamples: ...
    def memory_floats(self, pointer: Optional[int] = ...) -> FloatSamples: ...
    def state_text(self) -> str: ...

def cuda_runtime_version() -> int: ...
def cuda_driver_version() -> int: ...
def cuda_device_count() -> int: ...

def cuda_enabled() -> bool: ...

Simulator = CudaSimulator
